#!/bin/sh

while true; do
	read -p ">> " line
	if [ "$line" = '' ]; then exit; fi
	if [ -f compile ]; then
		echo $line | ./compile | runhaskell
	else
		echo $line | runhaskell compile.hs | runhaskell
	fi
done
